exclude = [
  "https://accounts.hetzner.com/login",
  "http://localhost:9093",
  "https://api.star-history.com/svg",
  "https://dash.cloudflare.com/profile/api-tokens",
  "https://console.ory.sh/",
  "https://username.github.io/REPOSITORY",
  "http://vmagent.localhost.com:8080/",
  ".*internal/rss-to-email-py/templates/%7B%7B%20UnsubscribeURL%20%7D%7D$",
  ".*internal/rss-to-email-py/templates/%7B%7B%20\\.Tx\\.Data\\..*%20%7D%7D",
  "https://(www\\.)?linkedin.com/in/meysamazad",
  "https://newsletter.developer-friendly.blog/subscription/form",
  ".*overrides/partials/%7B%7B%20author.avatar%20|%20url%20%7D%7D",
  ".*overrides/%7B%7B%20author.url%20%7D%7D",
  ".*overrides/partials/%7B%7B%20category.url%20|%20url%20%7D%7D",
  ".*overrides/partials/%7B%7B%20post.url%20|%20url%20%7D%7D",
  "docs/blog/category/",
  # TODO: remove this when he takes back his account
  "https://medium.com/@seifeddinerajhi/victoriametrics-a-comprehensive-guide-comparing-it-to-prometheus-and-implementing-kubernetes-03eb8feb0cc2",
  "https://github.com/developer-friendly/aws-lambda-opentofu-github-actions/actions/runs/.*",
  # Network error: Connection reset by server. Server forcibly closed connection
  # possibly some scraping/bot protection measures!
  "https://gateway-api.sigs.k8s.io/",
  "https://m.do.co/c/7de094ea6f0d",
  "https://cleanly-quiet-doberman.azureedge.net/",
  "https://www.freedesktop.org/software/systemd/man/latest/systemd.timer.html",
  "https://unsplash.com/photos/man-wearing-white-top-using-macbook-1K9T5YiZ2WU",
]

exclude_path = [
  "venv",
  "site",
  ".ruff_cache",
  "secrets",
  "internal/newsletter/index.html",
]

accept = [500, 429, 403, 200]

cache = true

max_cache_age = "7d"

timeout = 10

user_agent = "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
